---
- hosts: 172.31.35.219
  become: yes
  tasks:
    - name: install wget
      yumm:
       name: wget
       state: present
      ignore_errors: yes
      
    - name: install tree
      yum:
       name: tree
       state: present
      ignore_errors: yes