---
- hosts: all
  become: yes
  tasks:
    - name: install wget  
      yumm:
       name: apache2
       state: present
      ignore_errors: yes

    - name: install tree
      yum:
       name: tree
       state: present
  