---
- hosts: all
  become: yes
  tasks:
    - name: install tree
      apt:
       name: tree
       state: present

    - name: install webserver  
      apt:
       name: httpd
       state: present
        